#password 32d36f3e3e8a406c89818ab54021fb7e
# docker-compose.yaml

#sudo docker-compose up -d
 version: '3.8'
 services:
  jenkins:
   image: jenkins/jenkins:lts
   privileged: true
   user: root
   ports:
    - 8080:8080
    - 50000:50000
   container_name: jenkins
   volumes:
    - /home/ec2-user/jenkins_compose/jenkins_configuration:/var/jenkins_home
    - /var/run/docker.sock:/var/run/docker.sock



    #docker exec jenkins/jenkins:lts cat /var/jenkins_home/secrets/initialAdminPassword