version: '3.8'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:20.0.1
    commmand: start-dev
    enviroment:
     KC_DB: postgres
     KC_DB_URL_HOST: postgres
     KC_DB_URL_DATABASE: keycloak
     KC_DB_PASSWORD: password
     KC_DB_USERNAME: keycloak
     KC_DB_SCHEMA: public
     KEYCLOAK_ADMIN: admin 
     KEYCLOAK_ADMIN_PASSWORD: admin 
    ports:
     - "8080:8080"
    depends_on:
      postgres:
       condition: service_healthy
    
    networks:
     -keycloak_demo_dev_network

  
  postgres:
   image: postgres:14.2
   command: postgres -c 'max_connections=200'
   volumes:
    - pgdata:/var/Lib/postgressql/data
   enviroment:
    POSTGRES_DB: keycloak
    POSTGRES_USER: keycloak
    POSTGRES_PASSWORD: password
   healthcheck:
    test: "exit 0" 
   ports:
    - "5432:5432"

   networks:
    - keycloak_demo_dev_network

volumes:
 pgdata:
networks:
 keycloak_demo_dev_network:
  driver: bridge






    
